# Generated by Django 5.1.6 on 2025-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_providers',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
